baseURL = "https://nicolasparada.netlify.com/"
languageCode = "en-us"
title = "Nicolás Parada"
googleAnalytics = "UA-117854702-1"
[privacy]
  [privacy.googleAnalytics]
    anonymizeIP = true
    respectDoNotTrack = true
    useSessionStorage = true
